/**
 * Deutsche Städte für Local SEO
 * Alle Großstädte mit Umland für MyDispatch
 */

export interface GermanCity {
  name: string
  slug: string
  bundesland: string
  einwohner: number
  umland: string[]
  coordinates: {
    lat: number
    lng: number
  }
  beschreibung: string
  besonderheiten: string[]
}

export const GERMAN_CITIES: GermanCity[] = [
  // Top 20 Großstädte
  {
    name: "Berlin",
    slug: "berlin",
    bundesland: "Berlin",
    einwohner: 3645000,
    umland: ["Potsdam", "Oranienburg", "Bernau", "Königs Wusterhausen", "Teltow", "Falkensee"],
    coordinates: { lat: 52.52, lng: 13.405 },
    beschreibung: "Hauptstadt und größte Stadt Deutschlands mit über 3,6 Millionen Einwohnern",
    besonderheiten: ["Flughafen BER", "Messe Berlin", "Regierungsviertel", "Charité"],
  },
  {
    name: "Hamburg",
    slug: "hamburg",
    bundesland: "Hamburg",
    einwohner: 1841000,
    umland: ["Ahrensburg", "Norderstedt", "Pinneberg", "Buxtehude", "Wedel", "Reinbek"],
    coordinates: { lat: 53.5511, lng: 9.9937 },
    beschreibung: "Zweitgrößte Stadt Deutschlands und wichtigster Hafenstandort Europas",
    besonderheiten: ["Hamburger Hafen", "Flughafen Hamburg", "Messe Hamburg", "Elbphilharmonie"],
  },
  {
    name: "München",
    slug: "muenchen",
    bundesland: "Bayern",
    einwohner: 1472000,
    umland: ["Garching", "Freising", "Dachau", "Starnberg", "Erding", "Unterschleißheim"],
    coordinates: { lat: 48.1351, lng: 11.582 },
    beschreibung: "Drittgrößte Stadt Deutschlands und Wirtschaftsmetropole Bayerns",
    besonderheiten: ["Flughafen München", "Messe München", "BMW", "Siemens", "Oktoberfest"],
  },
  {
    name: "Köln",
    slug: "koeln",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 1084000,
    umland: ["Leverkusen", "Bergisch Gladbach", "Hürth", "Brühl", "Frechen", "Pulheim"],
    coordinates: { lat: 50.9375, lng: 6.9603 },
    beschreibung: "Viertgrößte Stadt Deutschlands und Medienstandort am Rhein",
    besonderheiten: ["Kölner Dom", "Flughafen Köln/Bonn", "Koelnmesse", "RTL", "WDR"],
  },
  {
    name: "Frankfurt am Main",
    slug: "frankfurt",
    bundesland: "Hessen",
    einwohner: 753000,
    umland: ["Offenbach", "Bad Homburg", "Oberursel", "Eschborn", "Neu-Isenburg", "Dreieich"],
    coordinates: { lat: 50.1109, lng: 8.6821 },
    beschreibung: "Finanzmetropole Deutschlands und Sitz der Europäischen Zentralbank",
    besonderheiten: ["Flughafen Frankfurt", "Messe Frankfurt", "Bankenviertel", "EZB"],
  },
  {
    name: "Stuttgart",
    slug: "stuttgart",
    bundesland: "Baden-Württemberg",
    einwohner: 634000,
    umland: ["Esslingen", "Ludwigsburg", "Böblingen", "Sindelfingen", "Fellbach", "Waiblingen"],
    coordinates: { lat: 48.7758, lng: 9.1829 },
    beschreibung: "Landeshauptstadt Baden-Württembergs und Automobilstandort",
    besonderheiten: ["Mercedes-Benz", "Porsche", "Flughafen Stuttgart", "Messe Stuttgart"],
  },
  {
    name: "Düsseldorf",
    slug: "duesseldorf",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 619000,
    umland: ["Neuss", "Ratingen", "Meerbusch", "Erkrath", "Hilden", "Langenfeld"],
    coordinates: { lat: 51.2277, lng: 6.7735 },
    beschreibung: "Landeshauptstadt NRW und internationale Messestadt",
    besonderheiten: ["Flughafen Düsseldorf", "Messe Düsseldorf", "Königsallee", "Medienhafen"],
  },
  {
    name: "Leipzig",
    slug: "leipzig",
    bundesland: "Sachsen",
    einwohner: 597000,
    umland: ["Halle", "Markkleeberg", "Taucha", "Schkeuditz", "Markranstädt"],
    coordinates: { lat: 51.3397, lng: 12.3731 },
    beschreibung: "Größte Stadt Sachsens und wachsende Metropole in Ostdeutschland",
    besonderheiten: ["Flughafen Leipzig/Halle", "Leipziger Messe", "BMW", "Porsche", "DHL Hub"],
  },
  {
    name: "Dortmund",
    slug: "dortmund",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 588000,
    umland: ["Bochum", "Hagen", "Unna", "Lünen", "Witten", "Castrop-Rauxel"],
    coordinates: { lat: 51.5136, lng: 7.4653 },
    beschreibung: "Größte Stadt im Ruhrgebiet und wichtiger Logistikstandort",
    besonderheiten: ["Westfalenhallen", "Signal Iduna Park", "Technologiepark"],
  },
  {
    name: "Essen",
    slug: "essen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 583000,
    umland: ["Mülheim", "Gelsenkirchen", "Oberhausen", "Bottrop", "Gladbeck"],
    coordinates: { lat: 51.4556, lng: 7.0116 },
    beschreibung: "Zentrale Stadt im Ruhrgebiet und ehemaliger Sitz von ThyssenKrupp",
    besonderheiten: ["Messe Essen", "Zeche Zollverein", "Grugapark"],
  },
  {
    name: "Bremen",
    slug: "bremen",
    bundesland: "Bremen",
    einwohner: 569000,
    umland: ["Bremerhaven", "Delmenhorst", "Achim", "Stuhr", "Lilienthal"],
    coordinates: { lat: 53.0793, lng: 8.8017 },
    beschreibung: "Hansestadt und wichtiger Standort der Automobil- und Luftfahrtindustrie",
    besonderheiten: ["Airbus", "Mercedes-Benz", "Überseestadt", "Universum Bremen"],
  },
  {
    name: "Dresden",
    slug: "dresden",
    bundesland: "Sachsen",
    einwohner: 556000,
    umland: ["Radebeul", "Freital", "Pirna", "Meißen", "Heidenau"],
    coordinates: { lat: 51.0504, lng: 13.7373 },
    beschreibung: "Landeshauptstadt Sachsens und Zentrum der Halbleiterindustrie",
    besonderheiten: ["Flughafen Dresden", "Infineon", "Globalfoundries", "VW Gläserne Manufaktur"],
  },
  {
    name: "Hannover",
    slug: "hannover",
    bundesland: "Niedersachsen",
    einwohner: 535000,
    umland: ["Langenhagen", "Laatzen", "Garbsen", "Lehrte", "Seelze", "Isernhagen"],
    coordinates: { lat: 52.3759, lng: 9.732 },
    beschreibung: "Landeshauptstadt Niedersachsens und internationaler Messestandort",
    besonderheiten: ["Hannover Messe", "CeBIT", "Flughafen Hannover", "VW Nutzfahrzeuge"],
  },
  {
    name: "Nürnberg",
    slug: "nuernberg",
    bundesland: "Bayern",
    einwohner: 518000,
    umland: ["Fürth", "Erlangen", "Schwabach", "Roth", "Zirndorf"],
    coordinates: { lat: 49.4521, lng: 11.0767 },
    beschreibung: "Zweitgrößte Stadt Bayerns und Wirtschaftszentrum Frankens",
    besonderheiten: ["Flughafen Nürnberg", "Nürnberg Messe", "Siemens", "Spielwarenmesse"],
  },
  {
    name: "Duisburg",
    slug: "duisburg",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 498000,
    umland: ["Moers", "Dinslaken", "Krefeld", "Oberhausen", "Mülheim"],
    coordinates: { lat: 51.4344, lng: 6.7623 },
    beschreibung: "Größter Binnenhafen Europas und Logistikzentrum",
    besonderheiten: ["Duisburger Hafen", "ThyssenKrupp Steel", "Landschaftspark Nord"],
  },
  {
    name: "Bochum",
    slug: "bochum",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 365000,
    umland: ["Herne", "Witten", "Hattingen", "Gelsenkirchen"],
    coordinates: { lat: 51.4818, lng: 7.2162 },
    beschreibung: "Universitätsstadt im Ruhrgebiet mit starkem Strukturwandel",
    besonderheiten: ["Ruhr-Universität", "Starlight Express", "Deutsches Bergbau-Museum"],
  },
  {
    name: "Wuppertal",
    slug: "wuppertal",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 355000,
    umland: ["Remscheid", "Solingen", "Velbert", "Schwelm"],
    coordinates: { lat: 51.2562, lng: 7.1508 },
    beschreibung: "Stadt der Schwebebahn und wichtiger Industriestandort im Bergischen Land",
    besonderheiten: ["Schwebebahn", "Bayer", "Tanztheater Pina Bausch"],
  },
  {
    name: "Bielefeld",
    slug: "bielefeld",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 334000,
    umland: ["Gütersloh", "Herford", "Bad Salzuflen", "Enger"],
    coordinates: { lat: 52.0302, lng: 8.5325 },
    beschreibung: "Größte Stadt in Ostwestfalen-Lippe und Maschinenbaustandort",
    besonderheiten: ["Dr. Oetker", "Schüco", "Universität Bielefeld"],
  },
  {
    name: "Bonn",
    slug: "bonn",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 331000,
    umland: ["Siegburg", "Königswinter", "Bad Honnef", "Sankt Augustin", "Troisdorf"],
    coordinates: { lat: 50.7374, lng: 7.0982 },
    beschreibung: "Ehemalige Bundeshauptstadt und UN-Standort",
    besonderheiten: ["Deutsche Telekom", "Deutsche Post", "UN Campus", "Flughafen Köln/Bonn"],
  },
  {
    name: "Münster",
    slug: "muenster",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 315000,
    umland: ["Greven", "Emsdetten", "Telgte", "Senden", "Havixbeck"],
    coordinates: { lat: 51.9607, lng: 7.6261 },
    beschreibung: "Universitätsstadt und lebenswerteste Stadt Deutschlands",
    besonderheiten: ["Westfälische Wilhelms-Universität", "Fahrradhauptstadt"],
  },
  // Weitere wichtige Städte
  {
    name: "Mannheim",
    slug: "mannheim",
    bundesland: "Baden-Württemberg",
    einwohner: 310000,
    umland: ["Ludwigshafen", "Heidelberg", "Weinheim", "Schwetzingen", "Viernheim"],
    coordinates: { lat: 49.4875, lng: 8.466 },
    beschreibung: "Industriestadt in der Metropolregion Rhein-Neckar",
    besonderheiten: ["BASF", "John Deere", "SAP Arena", "Mannheimer Hafen"],
  },
  {
    name: "Karlsruhe",
    slug: "karlsruhe",
    bundesland: "Baden-Württemberg",
    einwohner: 308000,
    umland: ["Ettlingen", "Rastatt", "Bruchsal", "Stutensee", "Rheinstetten"],
    coordinates: { lat: 49.0069, lng: 8.4037 },
    beschreibung: "Sitz des Bundesverfassungsgerichts und IT-Standort",
    besonderheiten: ["Bundesverfassungsgericht", "KIT", "dm-drogerie markt"],
  },
  {
    name: "Augsburg",
    slug: "augsburg",
    bundesland: "Bayern",
    einwohner: 296000,
    umland: ["Friedberg", "Königsbrunn", "Gersthofen", "Neusäß", "Stadtbergen"],
    coordinates: { lat: 48.3705, lng: 10.8978 },
    beschreibung: "Drittgrößte Stadt Bayerns mit reicher Industriegeschichte",
    besonderheiten: ["MAN", "KUKA", "Fuggerstadt", "Messe Augsburg"],
  },
  {
    name: "Wiesbaden",
    slug: "wiesbaden",
    bundesland: "Hessen",
    einwohner: 278000,
    umland: ["Mainz", "Taunusstein", "Bad Schwalbach", "Eltville", "Hochheim"],
    coordinates: { lat: 50.0826, lng: 8.2493 },
    beschreibung: "Landeshauptstadt Hessens und bedeutende Kurstadt",
    besonderheiten: ["Kurhaus", "Thermalbäder", "Statistisches Bundesamt"],
  },
  {
    name: "Mönchengladbach",
    slug: "moenchengladbach",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 261000,
    umland: ["Viersen", "Korschenbroich", "Jüchen", "Grevenbroich"],
    coordinates: { lat: 51.1805, lng: 6.4428 },
    beschreibung: "Textilstadt am Niederrhein mit starkem Mittelstand",
    besonderheiten: ["Textilindustrie", "Borussia Park"],
  },
  {
    name: "Gelsenkirchen",
    slug: "gelsenkirchen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 260000,
    umland: ["Buer", "Herten", "Gladbeck", "Bottrop"],
    coordinates: { lat: 51.5177, lng: 7.0857 },
    beschreibung: "Stadt im Strukturwandel mit starker Fußballtradition",
    besonderheiten: ["Veltins-Arena", "Zoom Erlebniswelt"],
  },
  {
    name: "Aachen",
    slug: "aachen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 249000,
    umland: ["Herzogenrath", "Würselen", "Stolberg", "Eschweiler", "Alsdorf"],
    coordinates: { lat: 50.7753, lng: 6.0839 },
    beschreibung: "Universitätsstadt und historische Kaiserstadt",
    besonderheiten: ["RWTH Aachen", "Aachener Dom", "Dreiländereck"],
  },
  {
    name: "Braunschweig",
    slug: "braunschweig",
    bundesland: "Niedersachsen",
    einwohner: 249000,
    umland: ["Wolfsburg", "Salzgitter", "Gifhorn", "Peine", "Helmstedt"],
    coordinates: { lat: 52.2689, lng: 10.5268 },
    beschreibung: "Forschungsstandort und Teil der Autostadt-Region",
    besonderheiten: ["Volkswagen", "TU Braunschweig", "PTB", "DLR"],
  },
  {
    name: "Chemnitz",
    slug: "chemnitz",
    bundesland: "Sachsen",
    einwohner: 244000,
    umland: ["Zwickau", "Freiberg", "Mittweida", "Limbach-Oberfrohna"],
    coordinates: { lat: 50.8278, lng: 12.9214 },
    beschreibung: "Industriestadt in Sachsen und Kulturhauptstadt Europas 2025",
    besonderheiten: ["Volkswagen Motorenwerk", "Kulturhauptstadt 2025"],
  },
  {
    name: "Kiel",
    slug: "kiel",
    bundesland: "Schleswig-Holstein",
    einwohner: 247000,
    umland: ["Eckernförde", "Rendsburg", "Plön", "Preetz", "Kronshagen"],
    coordinates: { lat: 54.3233, lng: 10.1228 },
    beschreibung: "Landeshauptstadt Schleswig-Holsteins und bedeutender Hafen",
    besonderheiten: ["Kieler Woche", "GEOMAR", "ThyssenKrupp Marine Systems"],
  },
  {
    name: "Magdeburg",
    slug: "magdeburg",
    bundesland: "Sachsen-Anhalt",
    einwohner: 236000,
    umland: ["Schönebeck", "Haldensleben", "Burg", "Wolmirstedt"],
    coordinates: { lat: 52.1205, lng: 11.6276 },
    beschreibung: "Landeshauptstadt Sachsen-Anhalts an der Elbe",
    besonderheiten: ["Grüne Zitadelle", "Otto-von-Guericke-Universität"],
  },
  {
    name: "Krefeld",
    slug: "krefeld",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 227000,
    umland: ["Meerbusch", "Willich", "Kempen", "Tönisvorst"],
    coordinates: { lat: 51.3388, lng: 6.5853 },
    beschreibung: "Samt- und Seidenstadt mit starker Textilindustrie",
    besonderheiten: ["Textilindustrie", "Krefelder Zoo"],
  },
  {
    name: "Freiburg im Breisgau",
    slug: "freiburg",
    bundesland: "Baden-Württemberg",
    einwohner: 231000,
    umland: ["Emmendingen", "Bad Krozingen", "Breisach", "March", "Gundelfingen"],
    coordinates: { lat: 47.999, lng: 7.8421 },
    beschreibung: "Universitätsstadt und Tor zum Schwarzwald",
    besonderheiten: ["Albert-Ludwigs-Universität", "Solarstadt", "Münster"],
  },
  {
    name: "Lübeck",
    slug: "luebeck",
    bundesland: "Schleswig-Holstein",
    einwohner: 217000,
    umland: ["Travemünde", "Bad Schwartau", "Stockelsdorf", "Ratekau"],
    coordinates: { lat: 53.8655, lng: 10.6866 },
    beschreibung: "Hansestadt und UNESCO-Weltkulturerbe",
    besonderheiten: ["Holstentor", "Marzipan", "Buddenbrookhaus"],
  },
  {
    name: "Erfurt",
    slug: "erfurt",
    bundesland: "Thüringen",
    einwohner: 214000,
    umland: ["Weimar", "Gotha", "Arnstadt", "Sömmerda"],
    coordinates: { lat: 50.9848, lng: 11.0299 },
    beschreibung: "Landeshauptstadt Thüringens mit historischer Altstadt",
    besonderheiten: ["Krämerbrücke", "Erfurter Dom", "egapark"],
  },
  {
    name: "Mainz",
    slug: "mainz",
    bundesland: "Rheinland-Pfalz",
    einwohner: 218000,
    umland: ["Wiesbaden", "Ingelheim", "Bingen", "Nieder-Olm", "Budenheim"],
    coordinates: { lat: 49.9929, lng: 8.2473 },
    beschreibung: "Landeshauptstadt von Rheinland-Pfalz und Medienstandort",
    besonderheiten: ["ZDF", "Mainzer Dom", "Gutenberg-Museum", "BioNTech"],
  },
  {
    name: "Rostock",
    slug: "rostock",
    bundesland: "Mecklenburg-Vorpommern",
    einwohner: 209000,
    umland: ["Warnemünde", "Bad Doberan", "Güstrow", "Sanitz"],
    coordinates: { lat: 54.0924, lng: 12.0991 },
    beschreibung: "Größte Stadt an der deutschen Ostseeküste",
    besonderheiten: ["Rostocker Hafen", "Kreuzfahrtterminal", "Universität Rostock"],
  },
  {
    name: "Kassel",
    slug: "kassel",
    bundesland: "Hessen",
    einwohner: 201000,
    umland: ["Baunatal", "Vellmar", "Lohfelden", "Niestetal", "Fuldabrück"],
    coordinates: { lat: 51.3127, lng: 9.4797 },
    beschreibung: "documenta-Stadt und Standort der Brüder Grimm",
    besonderheiten: ["documenta", "Bergpark Wilhelmshöhe", "VW Werk"],
  },
  {
    name: "Hagen",
    slug: "hagen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 189000,
    umland: ["Iserlohn", "Schwerte", "Herdecke", "Wetter", "Gevelsberg"],
    coordinates: { lat: 51.3671, lng: 7.4633 },
    beschreibung: "Tor zum Sauerland und Industriestadt",
    besonderheiten: ["FernUniversität", "Freilichtmuseum"],
  },
  {
    name: "Saarbrücken",
    slug: "saarbruecken",
    bundesland: "Saarland",
    einwohner: 180000,
    umland: ["Völklingen", "St. Ingbert", "Sulzbach", "Dudweiler"],
    coordinates: { lat: 49.2402, lng: 6.9969 },
    beschreibung: "Landeshauptstadt des Saarlands an der französischen Grenze",
    besonderheiten: ["Völklinger Hütte", "Saarländischer Rundfunk"],
  },
  {
    name: "Hamm",
    slug: "hamm",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 179000,
    umland: ["Ahlen", "Bergkamen", "Kamen", "Bönen"],
    coordinates: { lat: 51.6739, lng: 7.8159 },
    beschreibung: "Stadt im östlichen Ruhrgebiet mit großem Rangierbahnhof",
    besonderheiten: ["Maximilianpark", "Glaselefant"],
  },
  {
    name: "Ludwigshafen",
    slug: "ludwigshafen",
    bundesland: "Rheinland-Pfalz",
    einwohner: 172000,
    umland: ["Mannheim", "Frankenthal", "Speyer", "Schifferstadt"],
    coordinates: { lat: 49.4774, lng: 8.445 },
    beschreibung: "Industriestadt und Sitz der BASF",
    besonderheiten: ["BASF", "Wilhelm-Hack-Museum"],
  },
  {
    name: "Mühlheim an der Ruhr",
    slug: "muelheim",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 171000,
    umland: ["Essen", "Oberhausen", "Duisburg", "Ratingen"],
    coordinates: { lat: 51.4272, lng: 6.8825 },
    beschreibung: "Stadt zwischen Rhein und Ruhr",
    besonderheiten: ["Aldi Süd Zentrale", "Camera Obscura"],
  },
  {
    name: "Potsdam",
    slug: "potsdam",
    bundesland: "Brandenburg",
    einwohner: 183000,
    umland: ["Berlin", "Werder", "Teltow", "Kleinmachnow", "Stahnsdorf"],
    coordinates: { lat: 52.3906, lng: 13.0645 },
    beschreibung: "Landeshauptstadt Brandenburgs mit Schlössern und Gärten",
    besonderheiten: ["Schloss Sanssouci", "Filmstudio Babelsberg", "HPI"],
  },
  {
    name: "Leverkusen",
    slug: "leverkusen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 164000,
    umland: ["Köln", "Bergisch Gladbach", "Opladen", "Langenfeld"],
    coordinates: { lat: 51.0459, lng: 6.9877 },
    beschreibung: "Chemiestadt und Sitz von Bayer",
    besonderheiten: ["Bayer AG", "BayArena", "Chempark"],
  },
  {
    name: "Oldenburg",
    slug: "oldenburg",
    bundesland: "Niedersachsen",
    einwohner: 170000,
    umland: ["Bad Zwischenahn", "Rastede", "Wardenburg", "Hatten"],
    coordinates: { lat: 53.1435, lng: 8.2146 },
    beschreibung: "Universitätsstadt in Nordwestdeutschland",
    besonderheiten: ["Carl von Ossietzky Universität", "OFFIS"],
  },
  {
    name: "Osnabrück",
    slug: "osnabrueck",
    bundesland: "Niedersachsen",
    einwohner: 165000,
    umland: ["Bramsche", "Georgsmarienhütte", "Melle", "Bad Iburg"],
    coordinates: { lat: 52.2799, lng: 8.0472 },
    beschreibung: "Friedensstadt und Standort der Westfälischen Geschichte",
    besonderheiten: ["Westfälischer Friede", "Zoo Osnabrück", "VW Werk"],
  },
  {
    name: "Heidelberg",
    slug: "heidelberg",
    bundesland: "Baden-Württemberg",
    einwohner: 160000,
    umland: ["Mannheim", "Dossenheim", "Eppelheim", "Leimen", "Sandhausen"],
    coordinates: { lat: 49.3988, lng: 8.6724 },
    beschreibung: "Universitätsstadt mit weltberühmtem Schloss",
    besonderheiten: ["Ruprecht-Karls-Universität", "Heidelberger Schloss", "EMBL"],
  },
  {
    name: "Solingen",
    slug: "solingen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 159000,
    umland: ["Wuppertal", "Remscheid", "Leichlingen", "Haan"],
    coordinates: { lat: 51.1652, lng: 7.0671 },
    beschreibung: "Klingenstadt und Zentrum der Schneidwarenindustrie",
    besonderheiten: ["Schneidwarenindustrie", "Schloss Burg", "Seilbahn"],
  },
  {
    name: "Darmstadt",
    slug: "darmstadt",
    bundesland: "Hessen",
    einwohner: 159000,
    umland: ["Dieburg", "Griesheim", "Weiterstadt", "Pfungstadt", "Ober-Ramstadt"],
    coordinates: { lat: 49.8728, lng: 8.6512 },
    beschreibung: "Wissenschaftsstadt und Sitz von ESA und EUMETSAT",
    besonderheiten: ["TU Darmstadt", "ESA", "EUMETSAT", "Merck"],
  },
  {
    name: "Regensburg",
    slug: "regensburg",
    bundesland: "Bayern",
    einwohner: 153000,
    umland: ["Neutraubling", "Regenstauf", "Lappersdorf", "Pentling"],
    coordinates: { lat: 49.0134, lng: 12.1016 },
    beschreibung: "UNESCO-Welterbe und Universitätsstadt an der Donau",
    besonderheiten: ["Steinerne Brücke", "BMW Werk", "Continental"],
  },
  {
    name: "Herne",
    slug: "herne",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 156000,
    umland: ["Bochum", "Gelsenkirchen", "Recklinghausen", "Castrop-Rauxel"],
    coordinates: { lat: 51.5369, lng: 7.2211 },
    beschreibung: "Stadt im mittleren Ruhrgebiet",
    besonderheiten: ["Cranger Kirmes", "LWL-Museum für Archäologie"],
  },
  {
    name: "Neuss",
    slug: "neuss",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 153000,
    umland: ["Düsseldorf", "Meerbusch", "Kaarst", "Grevenbroich"],
    coordinates: { lat: 51.1984, lng: 6.6919 },
    beschreibung: "Hafenstadt am Rhein gegenüber von Düsseldorf",
    besonderheiten: ["Rheinhafen", "Quirinus-Münster"],
  },
  {
    name: "Paderborn",
    slug: "paderborn",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 152000,
    umland: ["Bad Lippspringe", "Delbrück", "Salzkotten", "Hövelhof"],
    coordinates: { lat: 51.7189, lng: 8.7575 },
    beschreibung: "Universitätsstadt und Sitz von Nixdorf",
    besonderheiten: ["Heinz Nixdorf MuseumsForum", "Universität Paderborn"],
  },
  {
    name: "Ingolstadt",
    slug: "ingolstadt",
    bundesland: "Bayern",
    einwohner: 138000,
    umland: ["Neuburg", "Eichstätt", "Pfaffenhofen", "Manching"],
    coordinates: { lat: 48.7665, lng: 11.4258 },
    beschreibung: "Audi-Stadt und bayerisches Wirtschaftszentrum",
    besonderheiten: ["Audi", "MediaMarktSaturn", "Festung"],
  },
  {
    name: "Offenbach",
    slug: "offenbach",
    bundesland: "Hessen",
    einwohner: 130000,
    umland: ["Frankfurt", "Hanau", "Mühlheim", "Obertshausen", "Heusenstamm"],
    coordinates: { lat: 50.0956, lng: 8.7761 },
    beschreibung: "Kreativstadt am Main im Rhein-Main-Gebiet",
    besonderheiten: ["Hochschule für Gestaltung", "Ledermuseum"],
  },
  {
    name: "Würzburg",
    slug: "wuerzburg",
    bundesland: "Bayern",
    einwohner: 127000,
    umland: ["Veitshöchheim", "Höchberg", "Gerbrunn", "Rottendorf"],
    coordinates: { lat: 49.7913, lng: 9.9534 },
    beschreibung: "Universitätsstadt in Franken mit barocker Residenz",
    besonderheiten: ["Residenz Würzburg", "Festung Marienberg", "Weinbau"],
  },
  {
    name: "Ulm",
    slug: "ulm",
    bundesland: "Baden-Württemberg",
    einwohner: 127000,
    umland: ["Neu-Ulm", "Blaustein", "Erbach", "Dornstadt"],
    coordinates: { lat: 48.4011, lng: 9.9876 },
    beschreibung: "Donaustadt mit dem höchsten Kirchturm der Welt",
    besonderheiten: ["Ulmer Münster", "Daimler Truck", "Science Park"],
  },
  {
    name: "Heilbronn",
    slug: "heilbronn",
    bundesland: "Baden-Württemberg",
    einwohner: 127000,
    umland: ["Neckarsulm", "Weinsberg", "Bad Rappenau", "Lauffen"],
    coordinates: { lat: 49.1427, lng: 9.211 },
    beschreibung: "Weinstadt am Neckar und Wirtschaftsstandort",
    besonderheiten: ["Audi", "Experimenta", "Bundesgartenschau 2019"],
  },
  {
    name: "Göttingen",
    slug: "goettingen",
    bundesland: "Niedersachsen",
    einwohner: 119000,
    umland: ["Bovenden", "Rosdorf", "Friedland", "Gleichen"],
    coordinates: { lat: 51.5413, lng: 9.9158 },
    beschreibung: "Universitätsstadt mit renommierter Georg-August-Universität",
    besonderheiten: ["Georg-August-Universität", "Max-Planck-Institute", "Sartorius"],
  },
  {
    name: "Wolfsburg",
    slug: "wolfsburg",
    bundesland: "Niedersachsen",
    einwohner: 124000,
    umland: ["Braunschweig", "Gifhorn", "Helmstedt", "Königslutter"],
    coordinates: { lat: 52.4227, lng: 10.7865 },
    beschreibung: "Autostadt und Volkswagen-Stammsitz",
    besonderheiten: ["Volkswagen", "Autostadt", "phaeno"],
  },
  {
    name: "Recklinghausen",
    slug: "recklinghausen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 111000,
    umland: ["Herten", "Marl", "Oer-Erkenschwick", "Datteln"],
    coordinates: { lat: 51.6141, lng: 7.1979 },
    beschreibung: "Stadt im nördlichen Ruhrgebiet",
    besonderheiten: ["Ruhrfestspiele", "Vestisches Museum"],
  },
  {
    name: "Pforzheim",
    slug: "pforzheim",
    bundesland: "Baden-Württemberg",
    einwohner: 126000,
    umland: ["Ispringen", "Birkenfeld", "Niefern", "Königsbach-Stein"],
    coordinates: { lat: 48.8922, lng: 8.6947 },
    beschreibung: "Goldstadt und Zentrum der Schmuckindustrie",
    besonderheiten: ["Schmuckindustrie", "Hochschule Pforzheim"],
  },
  {
    name: "Bottrop",
    slug: "bottrop",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 117000,
    umland: ["Oberhausen", "Gladbeck", "Essen", "Gelsenkirchen"],
    coordinates: { lat: 51.5247, lng: 6.9286 },
    beschreibung: "Stadt im westlichen Ruhrgebiet",
    besonderheiten: ["Movie Park", "Tetraeder", "Alpincenter"],
  },
  {
    name: "Bremerhaven",
    slug: "bremerhaven",
    bundesland: "Bremen",
    einwohner: 113000,
    umland: ["Cuxhaven", "Langen", "Geestland", "Schiffdorf"],
    coordinates: { lat: 53.5396, lng: 8.5809 },
    beschreibung: "Hafenstadt an der Wesermündung",
    besonderheiten: ["Klimahaus", "Deutsches Auswandererhaus", "Containerhafen"],
  },
  {
    name: "Remscheid",
    slug: "remscheid",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 111000,
    umland: ["Wuppertal", "Solingen", "Wermelskirchen", "Hückeswagen"],
    coordinates: { lat: 51.1787, lng: 7.1896 },
    beschreibung: "Werkzeugstadt im Bergischen Land",
    besonderheiten: ["Werkzeugindustrie", "Müngstener Brücke", "Röntgen-Museum"],
  },
  {
    name: "Fürth",
    slug: "fuerth",
    bundesland: "Bayern",
    einwohner: 129000,
    umland: ["Nürnberg", "Erlangen", "Zirndorf", "Oberasbach"],
    coordinates: { lat: 49.4774, lng: 10.9886 },
    beschreibung: "Nachbarstadt von Nürnberg in der Metropolregion",
    besonderheiten: ["Rundfunkmuseum", "Stadttheater"],
  },
  {
    name: "Trier",
    slug: "trier",
    bundesland: "Rheinland-Pfalz",
    einwohner: 111000,
    umland: ["Schweich", "Konz", "Hermeskeil", "Saarburg"],
    coordinates: { lat: 49.7596, lng: 6.6439 },
    beschreibung: "Älteste Stadt Deutschlands mit römischem Erbe",
    besonderheiten: ["Porta Nigra", "Trierer Dom", "Karl Marx Geburtshaus"],
  },
  {
    name: "Erlangen",
    slug: "erlangen",
    bundesland: "Bayern",
    einwohner: 113000,
    umland: ["Nürnberg", "Fürth", "Herzogenaurach", "Höchstadt"],
    coordinates: { lat: 49.5897, lng: 11.0078 },
    beschreibung: "Universitäts- und Siemens-Stadt in Mittelfranken",
    besonderheiten: ["Siemens Healthineers", "Friedrich-Alexander-Universität"],
  },
  {
    name: "Jena",
    slug: "jena",
    bundesland: "Thüringen",
    einwohner: 111000,
    umland: ["Weimar", "Apolda", "Kahla", "Eisenberg"],
    coordinates: { lat: 50.9271, lng: 11.5892 },
    beschreibung: "Optik- und Wissenschaftsstadt in Thüringen",
    besonderheiten: ["Carl Zeiss", "Jenoptik", "Friedrich-Schiller-Universität"],
  },
  {
    name: "Moers",
    slug: "moers",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 103000,
    umland: ["Duisburg", "Krefeld", "Kamp-Lintfort", "Neukirchen-Vluyn"],
    coordinates: { lat: 51.4517, lng: 6.6263 },
    beschreibung: "Stadt am linken Niederrhein",
    besonderheiten: ["Moerser Schloss", "Comedy Arts Festival"],
  },
  {
    name: "Salzgitter",
    slug: "salzgitter",
    bundesland: "Niedersachsen",
    einwohner: 104000,
    umland: ["Braunschweig", "Wolfenbüttel", "Goslar", "Peine"],
    coordinates: { lat: 52.1547, lng: 10.3292 },
    beschreibung: "Industriestadt mit Stahlproduktion",
    besonderheiten: ["Salzgitter AG", "Volkswagen"],
  },
  {
    name: "Siegen",
    slug: "siegen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 102000,
    umland: ["Netphen", "Kreuztal", "Freudenberg", "Wilnsdorf"],
    coordinates: { lat: 50.8748, lng: 8.0243 },
    beschreibung: "Universitätsstadt im Siegerland",
    besonderheiten: ["Universität Siegen", "Oberes Schloss"],
  },
  {
    name: "Hildesheim",
    slug: "hildesheim",
    bundesland: "Niedersachsen",
    einwohner: 101000,
    umland: ["Sarstedt", "Giesen", "Nordstemmen", "Harsum"],
    coordinates: { lat: 52.1508, lng: 9.9511 },
    beschreibung: "UNESCO-Welterbestadt mit romanischen Kirchen",
    besonderheiten: ["Mariendom", "St. Michaelis", "Roemer-Pelizaeus-Museum"],
  },
  {
    name: "Cottbus",
    slug: "cottbus",
    bundesland: "Brandenburg",
    einwohner: 99000,
    umland: ["Spremberg", "Forst", "Peitz", "Kolkwitz"],
    coordinates: { lat: 51.7606, lng: 14.3349 },
    beschreibung: "Größte Stadt der Lausitz",
    besonderheiten: ["BTU Cottbus-Senftenberg", "Staatstheater", "Lausitz"],
  },
  {
    name: "Gera",
    slug: "gera",
    bundesland: "Thüringen",
    einwohner: 93000,
    umland: ["Altenburg", "Zwickau", "Greiz", "Ronneburg"],
    coordinates: { lat: 50.8781, lng: 12.0831 },
    beschreibung: "Ehemalige Residenzstadt in Thüringen",
    besonderheiten: ["Villa Jahr", "Höhler", "Theater Gera"],
  },
  {
    name: "Gütersloh",
    slug: "guetersloh",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 100000,
    umland: ["Bielefeld", "Rheda-Wiedenbrück", "Verl", "Harsewinkel"],
    coordinates: { lat: 51.9066, lng: 8.3855 },
    beschreibung: "Medienstadt und Sitz von Bertelsmann",
    besonderheiten: ["Bertelsmann", "Miele", "Stadtpark"],
  },
  {
    name: "Witten",
    slug: "witten",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 96000,
    umland: ["Bochum", "Dortmund", "Hattingen", "Herdecke"],
    coordinates: { lat: 51.4436, lng: 7.3528 },
    beschreibung: "Stadt im südlichen Ruhrgebiet an der Ruhr",
    besonderheiten: ["Universität Witten/Herdecke", "Muttental"],
  },
  {
    name: "Iserlohn",
    slug: "iserlohn",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 92000,
    umland: ["Hagen", "Hemer", "Menden", "Schwerte"],
    coordinates: { lat: 51.3758, lng: 7.6947 },
    beschreibung: "Waldstadt im Sauerland",
    besonderheiten: ["Dechenhöhle", "Fachhochschule"],
  },
  {
    name: "Zwickau",
    slug: "zwickau",
    bundesland: "Sachsen",
    einwohner: 88000,
    umland: ["Werdau", "Crimmitschau", "Glauchau", "Wilkau-Haßlau"],
    coordinates: { lat: 50.7189, lng: 12.4963 },
    beschreibung: "Automobilstadt und Geburtsort von Robert Schumann",
    besonderheiten: ["Volkswagen Werk", "August Horch Museum"],
  },
  {
    name: "Schwerin",
    slug: "schwerin",
    bundesland: "Mecklenburg-Vorpommern",
    einwohner: 96000,
    umland: ["Wismar", "Parchim", "Ludwigslust", "Hagenow"],
    coordinates: { lat: 53.6355, lng: 11.4012 },
    beschreibung: "Landeshauptstadt Mecklenburg-Vorpommerns",
    besonderheiten: ["Schweriner Schloss", "Seen", "Staatstheater"],
  },
  {
    name: "Ratingen",
    slug: "ratingen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 87000,
    umland: ["Düsseldorf", "Mülheim", "Essen", "Heiligenhaus"],
    coordinates: { lat: 51.2966, lng: 6.8494 },
    beschreibung: "Stadt zwischen Düsseldorf und dem Bergischen Land",
    besonderheiten: ["LVR-Industriemuseum", "Grüne Hauptstadt 2017"],
  },
  {
    name: "Lünen",
    slug: "luenen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 85000,
    umland: ["Dortmund", "Bergkamen", "Selm", "Werne"],
    coordinates: { lat: 51.6167, lng: 7.5167 },
    beschreibung: "Stadt an der Lippe im östlichen Ruhrgebiet",
    besonderheiten: ["Seepark", "Colani-Ei"],
  },
  {
    name: "Esslingen",
    slug: "esslingen",
    bundesland: "Baden-Württemberg",
    einwohner: 93000,
    umland: ["Stuttgart", "Ostfildern", "Plochingen", "Nellingen"],
    coordinates: { lat: 48.7433, lng: 9.3048 },
    beschreibung: "Fachwerkstadt am Neckar bei Stuttgart",
    besonderheiten: ["Festo", "Mittelalterliche Altstadt", "Weihnachtsmarkt"],
  },
  {
    name: "Velbert",
    slug: "velbert",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 82000,
    umland: ["Wuppertal", "Essen", "Heiligenhaus", "Ratingen"],
    coordinates: { lat: 51.3396, lng: 7.0436 },
    beschreibung: "Schlüsselstadt und Zentrum der Schlossindustrie",
    besonderheiten: ["Schloss- und Beschlagindustrie", "Deutsches Schloss- und Beschlägemuseum"],
  },
  {
    name: "Marl",
    slug: "marl",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 84000,
    umland: ["Recklinghausen", "Herten", "Haltern", "Dorsten"],
    coordinates: { lat: 51.6567, lng: 7.0858 },
    beschreibung: "Chemiestadt im nördlichen Ruhrgebiet",
    besonderheiten: ["Chemiepark Marl", "Evonik"],
  },
  {
    name: "Villingen-Schwenningen",
    slug: "villingen-schwenningen",
    bundesland: "Baden-Württemberg",
    einwohner: 86000,
    umland: ["Donaueschingen", "Rottweil", "Tuttlingen", "Triberg"],
    coordinates: { lat: 48.0616, lng: 8.4934 },
    beschreibung: "Doppelstadt im Schwarzwald",
    besonderheiten: ["Uhrenindustrie", "DKFZ", "Schwarzwald"],
  },
  {
    name: "Minden",
    slug: "minden",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 82000,
    umland: ["Porta Westfalica", "Bad Oeynhausen", "Hille", "Petershagen"],
    coordinates: { lat: 52.2887, lng: 8.9172 },
    beschreibung: "Stadt an der Weser mit historischer Altstadt",
    besonderheiten: ["Wasserstraßenkreuz", "Mindener Dom"],
  },
  {
    name: "Konstanz",
    slug: "konstanz",
    bundesland: "Baden-Württemberg",
    einwohner: 85000,
    umland: ["Kreuzlingen (CH)", "Radolfzell", "Singen", "Allensbach"],
    coordinates: { lat: 47.6633, lng: 9.175 },
    beschreibung: "Universitätsstadt am Bodensee",
    besonderheiten: ["Bodensee", "Universität Konstanz", "Konzil"],
  },
  {
    name: "Neumünster",
    slug: "neumuenster",
    bundesland: "Schleswig-Holstein",
    einwohner: 80000,
    umland: ["Kiel", "Bad Segeberg", "Rendsburg", "Plön"],
    coordinates: { lat: 54.0703, lng: 9.9872 },
    beschreibung: "Kreisfreie Stadt in Schleswig-Holstein",
    besonderheiten: ["Holstenhallen", "Tierpark Neumünster"],
  },
  {
    name: "Norderstedt",
    slug: "norderstedt",
    bundesland: "Schleswig-Holstein",
    einwohner: 80000,
    umland: ["Hamburg", "Quickborn", "Henstedt-Ulzburg", "Kaltenkirchen"],
    coordinates: { lat: 53.7064, lng: 9.9864 },
    beschreibung: "Stadt im Hamburger Umland",
    besonderheiten: ["Stadtpark", "Arriba Erlebnisbad"],
  },
  {
    name: "Delmenhorst",
    slug: "delmenhorst",
    bundesland: "Niedersachsen",
    einwohner: 78000,
    umland: ["Bremen", "Oldenburg", "Ganderkesee", "Stuhr"],
    coordinates: { lat: 53.0506, lng: 8.6317 },
    beschreibung: "Stadt zwischen Bremen und Oldenburg",
    besonderheiten: ["Nordwolle", "Burginsel"],
  },
  {
    name: "Wilhelmshaven",
    slug: "wilhelmshaven",
    bundesland: "Niedersachsen",
    einwohner: 76000,
    umland: ["Schortens", "Sande", "Jever", "Varel"],
    coordinates: { lat: 53.5286, lng: 8.1067 },
    beschreibung: "Marinestadt und Hafenstandort an der Nordsee",
    besonderheiten: ["JadeWeserPort", "Deutsches Marinemuseum"],
  },
  {
    name: "Gladbeck",
    slug: "gladbeck",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 75000,
    umland: ["Bottrop", "Gelsenkirchen", "Essen", "Dorsten"],
    coordinates: { lat: 51.5706, lng: 6.9858 },
    beschreibung: "Stadt im nördlichen Ruhrgebiet",
    besonderheiten: ["Wasserschloss Wittringen", "Jovypark"],
  },
  {
    name: "Viersen",
    slug: "viersen",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 77000,
    umland: ["Mönchengladbach", "Krefeld", "Willich", "Nettetal"],
    coordinates: { lat: 51.2539, lng: 6.3942 },
    beschreibung: "Stadt am linken Niederrhein",
    besonderheiten: ["Hoher Busch", "Süchtelner Höhen"],
  },
  {
    name: "Troisdorf",
    slug: "troisdorf",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 75000,
    umland: ["Siegburg", "Bonn", "Sankt Augustin", "Niederkassel"],
    coordinates: { lat: 50.8144, lng: 7.1558 },
    beschreibung: "Industriestadt im Rhein-Sieg-Kreis",
    besonderheiten: ["Wahner Heide", "Industriestandort"],
  },
  {
    name: "Dorsten",
    slug: "dorsten",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 74000,
    umland: ["Marl", "Haltern", "Gelsenkirchen", "Bottrop"],
    coordinates: { lat: 51.6614, lng: 6.9644 },
    beschreibung: "Stadt am Rande des Ruhrgebiets",
    besonderheiten: ["Lippetal", "Jüdisches Museum"],
  },
  {
    name: "Arnsberg",
    slug: "arnsberg",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 73000,
    umland: ["Meschede", "Sundern", "Ense", "Wickede"],
    coordinates: { lat: 51.3962, lng: 8.0658 },
    beschreibung: "Stadt im Sauerland an der Ruhr",
    besonderheiten: ["Schloss Arnsberg", "Sauerland-Museum"],
  },
  {
    name: "Detmold",
    slug: "detmold",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 74000,
    umland: ["Lemgo", "Horn-Bad Meinberg", "Lage", "Blomberg"],
    coordinates: { lat: 51.9386, lng: 8.8783 },
    beschreibung: "Residenzstadt in Ostwestfalen-Lippe",
    besonderheiten: ["Hermannsdenkmal", "Landestheater", "Residenzschloss"],
  },
  {
    name: "Lüdenscheid",
    slug: "luedenscheid",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 72000,
    umland: ["Meinerzhagen", "Halver", "Altena", "Werdohl"],
    coordinates: { lat: 51.2197, lng: 7.6275 },
    beschreibung: "Stadt der Lichttechnik im Märkischen Kreis",
    besonderheiten: ["Lichttechnikindustrie", "Phänomenta"],
  },
  {
    name: "Castrop-Rauxel",
    slug: "castrop-rauxel",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 73000,
    umland: ["Dortmund", "Herne", "Recklinghausen", "Waltrop"],
    coordinates: { lat: 51.5497, lng: 7.3108 },
    beschreibung: "Stadt im mittleren Ruhrgebiet",
    besonderheiten: ["Zeche Erin", "Europäischer Kulturpark"],
  },
  {
    name: "Landshut",
    slug: "landshut",
    bundesland: "Bayern",
    einwohner: 73000,
    umland: ["Ergolding", "Altdorf", "Kumhausen", "Essenbach"],
    coordinates: { lat: 48.5369, lng: 12.1522 },
    beschreibung: "Regierungshauptstadt Niederbayerns",
    besonderheiten: ["Landshuter Hochzeit", "Burg Trausnitz", "BMW Werk"],
  },
  {
    name: "Rheine",
    slug: "rheine",
    bundesland: "Nordrhein-Westfalen",
    einwohner: 76000,
    umland: ["Greven", "Emsdetten", "Neuenkirchen", "Hörstel"],
    coordinates: { lat: 52.2814, lng: 7.4378 },
    beschreibung: "Stadt an der Ems im Münsterland",
    besonderheiten: ["NaturZoo Rheine", "Saline Gottesgabe"],
  },
  {
    name: "Kempten",
    slug: "kempten",
    bundesland: "Bayern",
    einwohner: 70000,
    umland: ["Durach", "Waltenhofen", "Buchenberg", "Wiggensbach"],
    coordinates: { lat: 47.7267, lng: 10.3168 },
    beschreibung: "Größte Stadt im Allgäu",
    besonderheiten: ["Allgäu", "Archäologischer Park", "St. Lorenz"],
  },
  {
    name: "Fulda",
    slug: "fulda",
    bundesland: "Hessen",
    einwohner: 69000,
    umland: ["Petersberg", "Künzell", "Eichenzell", "Hünfeld"],
    coordinates: { lat: 50.5528, lng: 9.6758 },
    beschreibung: "Barockstadt und Bischofsstadt in Osthessen",
    besonderheiten: ["Fuldaer Dom", "Barockviertel", "Hochschule Fulda"],
  },
  {
    name: "Bamberg",
    slug: "bamberg",
    bundesland: "Bayern",
    einwohner: 77000,
    umland: ["Hallstadt", "Bischberg", "Memmelsdorf", "Strullendorf"],
    coordinates: { lat: 49.8988, lng: 10.9028 },
    beschreibung: "UNESCO-Welterbestadt mit mittelalterlicher Altstadt",
    besonderheiten: ["Bamberger Dom", "Altes Rathaus", "Rauchbier"],
  },
  {
    name: "Passau",
    slug: "passau",
    bundesland: "Bayern",
    einwohner: 53000,
    umland: ["Vilshofen", "Hauzenberg", "Thyrnau", "Obernzell"],
    coordinates: { lat: 48.5667, lng: 13.4319 },
    beschreibung: "Dreiflüssestadt an der österreichischen Grenze",
    besonderheiten: ["Stephansdom", "Drei Flüsse", "Veste Oberhaus"],
  },
  {
    name: "Bayreuth",
    slug: "bayreuth",
    bundesland: "Bayern",
    einwohner: 74000,
    umland: ["Bindlach", "Eckersdorf", "Heinersreuth", "Mistelgau"],
    coordinates: { lat: 49.9456, lng: 11.5713 },
    beschreibung: "Festspielstadt und Universitätsstadt in Oberfranken",
    besonderheiten: ["Richard-Wagner-Festspiele", "Markgräfliches Opernhaus"],
  },
  {
    name: "Plauen",
    slug: "plauen",
    bundesland: "Sachsen",
    einwohner: 65000,
    umland: ["Oelsnitz", "Reichenbach", "Greiz", "Auerbach"],
    coordinates: { lat: 50.4939, lng: 12.1297 },
    beschreibung: "Spitzenstadt im Vogtland",
    besonderheiten: ["Plauener Spitze", "Vogtlandtheater"],
  },
  {
    name: "Friedrichshafen",
    slug: "friedrichshafen",
    bundesland: "Baden-Württemberg",
    einwohner: 62000,
    umland: ["Ravensburg", "Tettnang", "Meckenbeuren", "Markdorf"],
    coordinates: { lat: 47.6561, lng: 9.4789 },
    beschreibung: "Zeppelin-Stadt am Bodensee",
    besonderheiten: ["ZF Friedrichshafen", "Zeppelin Museum", "Messe Friedrichshafen"],
  },
  {
    name: "Görlitz",
    slug: "goerlitz",
    bundesland: "Sachsen",
    einwohner: 57000,
    umland: ["Zgorzelec (PL)", "Reichenbach", "Löbau", "Niesky"],
    coordinates: { lat: 51.1536, lng: 14.9878 },
    beschreibung: "Östlichste Stadt Deutschlands an der Neiße",
    besonderheiten: ["Europastadt", "Historische Altstadt", "Filmkulisse"],
  },
  {
    name: "Stralsund",
    slug: "stralsund",
    bundesland: "Mecklenburg-Vorpommern",
    einwohner: 59000,
    umland: ["Greifswald", "Ribnitz-Damgarten", "Bergen auf Rügen"],
    coordinates: { lat: 54.3092, lng: 13.0819 },
    beschreibung: "Hansestadt und Tor zur Insel Rügen",
    besonderheiten: ["Ozeaneum", "Historische Altstadt", "Rügendamm"],
  },
  {
    name: "Greifswald",
    slug: "greifswald",
    bundesland: "Mecklenburg-Vorpommern",
    einwohner: 59000,
    umland: ["Stralsund", "Anklam", "Wolgast", "Lubmin"],
    coordinates: { lat: 54.0924, lng: 13.3877 },
    beschreibung: "Universitäts- und Hansestadt an der Ostsee",
    besonderheiten: ["Ernst-Moritz-Arndt-Universität", "Caspar David Friedrich"],
  },
]

// Sortiert nach Einwohnerzahl (absteigend)
export const GERMAN_CITIES_SORTED = [...GERMAN_CITIES].sort((a, b) => b.einwohner - a.einwohner)

// Für SEO: Generiert alle Städte-Slugs
export function getAllCitySlugs(): string[] {
  return GERMAN_CITIES.map((city) => city.slug)
}

// Findet eine Stadt nach Slug
export function getCityBySlug(slug: string): GermanCity | undefined {
  return GERMAN_CITIES.find((city) => city.slug === slug)
}

// Gibt die ersten n Städte zurück (für "Mehr laden")
export function getCitiesSubset(count: number): GermanCity[] {
  return GERMAN_CITIES_SORTED.slice(0, count)
}
