export const ALL_TARIFFS = [
  {
    id: "starter",
    name: "Starter",
    description: "Perfekt für kleine Flotten",
    priceMonthlyFormatted: "39€",
    priceYearlyFormatted: "374€",
    ctaText: "Jetzt starten",
    highlighted: false,
    features: [
      { name: "Bis zu 3 Fahrzeuge", included: true },
      { name: "Bis zu 3 Fahrer", included: true },
      { name: "Auftragsverwaltung", included: true },
      { name: "Basis-Reporting", included: true },
      { name: "Email-Support", included: true },
    ],
  },
  {
    id: "business",
    name: "Business",
    description: "Für wachsende Unternehmen",
    priceMonthlyFormatted: "99€",
    priceYearlyFormatted: "950€",
    badge: "Beliebt",
    ctaText: "Jetzt starten",
    highlighted: true,
    features: [
      { name: "Unbegrenzte Fahrzeuge", included: true },
      { name: "Unbegrenzte Fahrer", included: true },
      { name: "Alle Starter-Features", included: true },
      { name: "Erweiterte Statistiken", included: true },
      { name: "Partner-Management", included: true },
      { name: "Kundenportal", included: true },
      { name: "API-Zugang", included: true },
      { name: "Telefon-Support", included: true },
      { name: "Live-Tracking", included: true },
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "Für große Flotten",
    priceMonthlyFormatted: "Individuell",
    priceYearlyFormatted: "Individuell",
    ctaText: "Kontakt aufnehmen",
    highlighted: false,
    features: [
      { name: "Unbegrenzte Fahrzeuge", included: true },
      { name: "Unbegrenzte Fahrer", included: true },
      { name: "Alle Business-Features", included: true },
      { name: "Dedizierter Account Manager", included: true },
      { name: "Custom Integrationen", included: true },
      { name: "SLA Garantie", included: true },
    ],
  },
]
